<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Рецепты");
?><?
$APPLICATION->IncludeComponent("bbc:elements", "recipes", array(
    "IBLOCK_TYPE" => "recipes",//
    "IBLOCK_ID" => \Local\iBlockData::getIblockIDByCode("recipes"),
    "TEMPLATE_THEME" => "site",
    "USE_SEARCH" => "N",
    "USE_RSS" => "Y",
    "USE_RATING" => "N",
    "USE_CATEGORIES" => "N",
    "USE_REVIEW" => "N",
    "USE_FILTER" => "N",
    "ELEMENTS_COUNT" => "10",
    "SORT_BY1" => "ACTIVE_FROM",
    "SORT_ORDER1" => "DESC",
    "SORT_BY2" => "SORT",
    "SORT_ORDER2" => "ASC",
    "CHECK_DATES" => "Y",
    "SEF_MODE" => "Y",
    "SEF_FOLDER" => "/recipes/",
    "AJAX_MODE" => "N",
    "AJAX_OPTION_SHADOW" => "Y",
    "AJAX_OPTION_JUMP" => "N",
    "AJAX_OPTION_STYLE" => "Y",
    "AJAX_OPTION_HISTORY" => "N",
    "CACHE_TYPE" => "A",
    "CACHE_TIME" => "36000000",
    "CACHE_FILTER" => "N",
    "CACHE_GROUPS" => "Y",
    "DISPLAY_PANEL" => "Y",
    "SET_TITLE" => "Y",
    "SET_STATUS_404" => "Y",
    "INCLUDE_IBLOCK_INTO_CHAIN" => "N",
    "ADD_SECTIONS_CHAIN" => "N",
    "ADD_ELEMENT_CHAIN" => "Y",
    "USE_PERMISSIONS" => "N",
    "PREVIEW_TRUNCATE_LEN" => "",
    "LIST_DATE_FORMAT" => "d.m.Y",
    "DETAIL_DATE_FORMAT" => "d.m.Y",
    "LIST_SELECT_PROPS" => array(
        0 => "INGREDIENTS",
        1 => "",
    ),
    "LIST_SELECT_FIELDS" => array(
        0 => "NAME",
        1 => "PREVIEW_TEXT",
        2 => "DETAIL_TEXT",
        3 => "PREVIEW_PICTURE",
        4 => "DETAIL_PICTURE",
        5 => "IBLOCK_ID",
        6 => "ACTIVE_FROM",
        7 => "CREATED_USER_NAME",
        8 => "DATE_CREATE"
    ),
    "LIST_RESULT_PROCESSING_MODE" => "EXTENDED",
    "DETAIL_RESULT_PROCESSING_MODE" => "EXTENDED",
    "DETAIL_SELECT_PROPS" => array(
        0 => "INGREDIENTS",
        1 => "",
    ),
    "DETAIL_SELECT_FIELDS" => array(
        0 => "NAME",
        1 => "PREVIEW_TEXT",
        2 => "DETAIL_TEXT",
        3 => "PREVIEW_PICTURE",
        4 => "DETAIL_PICTURE",
        5 => "IBLOCK_ID",
        6 => "ACTIVE_FROM",
        7 => "CREATED_USER_NAME",
        8 => "DATE_CREATE"
    ),
    "HIDE_LINK_WHEN_NO_DETAIL" => "N",
    "DISPLAY_NAME" => "Y",
    "META_KEYWORDS" => "-",
    "META_DESCRIPTION" => "-",
    "BROWSER_TITLE" => "-",
    "DETAIL_DATE_FORMAT" => "d.m.Y",
    "DETAIL_DISPLAY_TOP_PAGER" => "N",
    "DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
    "DETAIL_PAGER_TITLE" => "Страница",
    "DETAIL_PAGER_TEMPLATE" => "arrows",
    "DETAIL_PAGER_SHOW_ALL" => "Y",
    "DISPLAY_TOP_PAGER" => "N",
    "DISPLAY_BOTTOM_PAGER" => "Y",
    "PAGER_TITLE" => "Рецепты",
    "PAGER_SHOW_ALWAYS" => "N",
    "PAGER_TEMPLATE" => "arrows_recipes",
    "PAGER_DESC_NUMBERING" => "N",
    "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000000",
    "PAGER_SHOW_ALL" => "N",
    "LIST_DISPLAY_DATE" => "Y",
    "DETAIL_DISPLAY_DATE" => "Y",
    "DISPLAY_PICTURE" => "Y",
    "DETAIL_DISPLAY_PICTURE" => "Y",
    "DISPLAY_PREVIEW_TEXT" => "Y",
    "AJAX_OPTION_ADDITIONAL" => "",
    "SLIDER_PROPERTY" => "PICS_NEWS",
    "SEF_URL_TEMPLATES" => array(
        "news" => "",
        "section" => "",
        "detail" => "#ELEMENT_CODE#/",
        "search" => "search/",
        "rss" => "rss/",
        "rss_section" => "#SECTION_ID#/rss/",
    ),
    "CURRENT_MAIN_PAGE_URL" => ""
),
    false
); ?><? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>